#!/usr/bin/env bash

set -eux

cd "${BASH_SOURCE%/*}"

test -t 1 && OPTS='-it' || OPTS=''

# after we have official docker repository, we will switch to use official docker image
SPHINX_IMAGE=${SPHINX_IMAGE:-cnuliuweiren/sphinx:1.0}

docker run --rm $OPTS -e CHUNJUN_VERSION -u $(id -u):$(id -g) -v "$PWD":/docs $SPHINX_IMAGE \
  sphinx-build -q -j auto -b html -W -d target/doctrees src/main/sphinx target/html
